### ISSUE TITLE
Mention this module in Related projects of wl-clipboard

### ISSUE THREAD

**Issue by dumblob** [asvvvad/vlipboard#1]
See https://github.com/bugaevc/wl-clipboard#related-projects - would be cool to link this repo there.

**Comment by asvvvad1** [comment]
Sorry for the very late reply and thanks for your suggestion!
I made a pull request to add this repo there as you suggested ^^

**Comment by asvvvad1** [comment]
from https://github.com/bugaevc/wl-clipboard/pull/84#issuecomment-632001274:
>Unfortunately I'm not going to accept this. This is not because you did anything wrong; rather, the list of related projects is not what it appears to be. It's not, and it's not meant to be, a comprehensive list of all the projects that use wl-clipboard — there are many ad-hoc clipboard managers that are based on wl-clipboard on GitHub alone.
Thanks for the suggestion anyway!

**Comment by dumblob** [comment]
Ah, ok. Didn't appear to me it's not the goal of the readme section. But at least we tried :wink:.
